version: '3.9'

services:
  MicroserviceSubscription:
    image: microservicesubscription_img
    build: ./MicroserviceSubscription
    container_name: subscription
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://Eurikaserver:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://MySQL:3306/MicroserviceSubscription?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - Eurikaserver
      - MySQL

  
  Eurikaserver:
   build: ./EurekaServer
   image: eureka_img
   container_name: eureka
   ports:
      - "8761:8761"
 

  Apigateway:
    build: ./ApiGateway
    image: apigateway_img
    container_name: apigateway
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://Eurikaserver:8761/eureka
    depends_on:
      - Eurikaserver
      - MicroserviceSubscription

  MySQL:
    image: "mysql:5.6"
    container_name: mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
   
    environment:
    - MYSQL_ROOT_PASSWORD=root
      
  

