version: '3.9'

services:

  MicroserviceSubscription:
    image: microservicesubscription_img
    build: ./Sarra./MicroserviceSubscription
    container_name: subscription
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://MySQL:3306/MicroserviceSubscription?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eurekaserver
      - MySQL

  courses:
    build : ./Yasmine./MicroServiceProject
    image: course
    container_name: course-container
    ports:
      - "8077:8077"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
    depends_on:
      - eurekaserver

  MicroserviceReclamation:
    image: microservicereclamation_img
    build: ./Haithem./MicroServiceProject
    container_name: reclamation
    ports:
      - "8076:8076"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_DATASOURCE_URL=jdbc:mysql://MySQL:3306/MicroService?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - eurekaserver
      - MySQL

  pistes:
    build : ./MicroServiceProject
    image: piste
    container_name: piste-container
    ports:
      - "8075:8075"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver

  eurekaserver:
    build:
      context: ./ErekaServer
      dockerfile: Dockerfile
    image: eureka
    container_name: eureka-container
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/

  api-gateway:
    build: ./APIGateway
    image: gateway
    container_name: gateway-container
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka/
    depends_on:
      - eurekaserver
      - pistes
      - MicroserviceReclamation
      - courses
      - MicroserviceSubscription
  
  MySQL:
    image: "mysql:5.6"
    container_name: mysql
    ports:
      - "3307:3306"
    restart: unless-stopped
   
    environment:
    - MYSQL_ROOT_PASSWORD=root